version: "3"
services:
  nodeapi: 
    container_name: nodeapi
    restart: always
    build: .
    ports: 
      - "4000:3000"
    links: 
      - mongodb
    volumes:
      - .:/usr/src/app
  mongodb:
    container_name: mongodatabase
    image: mongo
    ports: 
      - 27017:27017
    logging:
      driver: none
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongoexpress:
    image: mongo-express
    ports: 
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
