swagger: '2.0'
info:
  title: Sample api
  description: adasdasd
servers:
  - url: http://localhost:3000 
paths:
  /courses:
     get:
       summary: asdasd
       description: asdasdasd
       responses:
         '200':
           description: saddssdf
            